{% set name = "html-pipeline" %}
{% set version = "2.14.1" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 1c8178dcd1fa675bcf5540cf77a48a46a9c97e9cd170ddb50f85bb6a3716acd9

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby
    - rb-activesupport >=2
    - rb-nokogiri >=1.4

test:
  commands:
    - ruby -r {{ name|replace('-','/') }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: {{ name }}-{{ version }}/LICENSE
  summary: GitHub HTML processing filters and utilities

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/jch/{{ name }}

extra:
  recipe-maintainers:
    - sodre
