travis:
  secure:
    BINSTAR_TOKEN: GLD706liIen6qD8llQcIqSJIIZQgnS9gZtmqwMg3iK5n318NFketMFJMp8Ch+8ShejksXk6c/vYC6LkZ8h2HVTqyKouPZ1txBSlpTB61Hx5RAQR6Tgeydw/xP8sWK30AaxlIRA6yDu/YuBI04Lm6q7j20oj5+Ut/WvgsCQnh7CziBG22cW5C2dt3Wgl46B89tUn4cEqtL0RNQCqC/YxKvWndTizO0NPj3ZRw+5JWR3N8/yReHCI5aGNWs4A780UMGgMNJFWYq6/B8Gl8IJz4iJw+21Dn2wg3+BypWRt/9Ao0HiNUHL2pc3iq7sfgTsOeQKHdL933ZMoh6fNR2SLmmEHCJDYiq9v5UUSYaReOi73lTOzIj+SM4p92VmcXCENtT4H2Ml+LsSorhEm30kWPz5tXRspOOmUKIOhVjhcaVslswjzsU014b9zUQUZ0NK2DPqPxcpcZ9z+NnA/zcvR8sDlQ35I0MD57bF1bRqAHVHzDzY5dcWoIfT7atoTR1wLGJh4XvVBT9sZkA58goSQ7AApdMgMKTJBXuW6/lNtY9x9JppJfd5QnXrh63Wx+0D58m0JI2x5LPI+378NmUoTVh1QtGBTfYgL60/O1C7KKQHI3J7pgbi8nbJbxP03XQfFcr6tyeKa8lUuRpco6DLN/43zT9boUmPeTFIZ3d2Xa+Pc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
