travis:
  secure:
    BINSTAR_TOKEN: q1FaMNCxdMp3i4fagiXnZTvUqiITChoaRivfJjHCA/jUBkwMyTb9Yjx4NQ5FTEKMr0ltDfIgQYSLSrkPiICnJnlcO/l0af3k0UMyZvKilzQauxjJK6HoWGf79nKWhkVt87ciOR3WGKFJdqUCn0thpyR2BUCgs+OhyUxIbTDtSJ9TnEYoQ7BbrAKMzlN9j0GZpABras1PuXV+wEvK5E1vJImMn27cTNvrJrvkJQS9NDY3TYvnP7xG4I20jM6EwhZtQ24YWtMV6o+OwfB8SYMFveu6QE5czrvSrDqdBU9ffCVUOyJE6fnQjKZjuo1bjKFyg9ptWeOHZIGw7EhI8Zo/OIWbutxqZPx0Ls9/+QqmUdRRdxIXwLTFJ00wmzxx69hZWG/IOlFH2vPjiE8RvakG/tET4b3yAMw7oV/pGMWOADgCC0XBqsX5a3xYXuokqfDUOZi0bDu+SEZ30z37E106oNNSxleOCbeSULYMGk96YOq2dYW0VvrVErmx+OBx/+4G693Amfm1XzjLAVap6wayAvcgnvcvhci54iKwsezmTkYB/tUCicRlVCJTLJgyZSfp7Uv2PrGbBniOMGfAUzADkylV6+S+AlohnC9fPjAtE6c4IYr8ccKurysgi9p7avAMjKSLfSAXrGxSzM8WXawPyFWkndFCO/YSCnPZr5gkhso=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
